-- MySQL Script generated by MySQL Workbench
-- Sat Dec 24 23:37:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`blood_donors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`blood_donors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`blood_donors` (
  `DonorID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `contactNo` INT NOT NULL,
  PRIMARY KEY (`DonorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recipients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recipients` (
  `recipientsID` INT NOT NULL AUTO_INCREMENT,
  `bloodType` VARCHAR(45) NOT NULL,
  `contactNO` INT NOT NULL,
  `quantityBlood` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recipientsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blood`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Blood` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Blood` (
  `stockID` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `blood_group` VARCHAR(45) NOT NULL,
  `blood_donors_DonorID` INT NOT NULL,
  `recipients_recipientsID` INT NOT NULL,
  PRIMARY KEY (`stockID`),
  INDEX `fk_Blood_blood donors_idx` (`blood_donors_DonorID` ASC) VISIBLE,
  INDEX `fk_Blood_recipients1_idx` (`recipients_recipientsID` ASC) VISIBLE,
  CONSTRAINT `fk_Blood_blood donors`
    FOREIGN KEY (`blood_donors_DonorID`)
    REFERENCES `mydb`.`blood_donors` (`DonorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Blood_recipients1`
    FOREIGN KEY (`recipients_recipientsID`)
    REFERENCES `mydb`.`recipients` (`recipientsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seeker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`seeker` ;

CREATE TABLE IF NOT EXISTS `mydb`.`seeker` (
  `seekerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `bloodgroup` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `phoneNO` INT NOT NULL,
  PRIMARY KEY (`seekerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hospital` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hospital` (
  `hospital_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phoneNo` INT NOT NULL,
  PRIMARY KEY (`hospital_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `requestID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `requiredBlood` VARCHAR(45) NOT NULL,
  `memberType` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `contactNO` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `seeker_seekerID` INT NOT NULL,
  PRIMARY KEY (`requestID`),
  INDEX `fk_Request_seeker1_idx` (`seeker_seekerID` ASC) VISIBLE,
  CONSTRAINT `fk_Request_seeker1`
    FOREIGN KEY (`seeker_seekerID`)
    REFERENCES `mydb`.`seeker` (`seekerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospital_has_Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hospital_has_Request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hospital_has_Request` (
  `Hospital_hospital_ID` INT NOT NULL,
  `Request_requestID` INT NOT NULL,
  PRIMARY KEY (`Hospital_hospital_ID`, `Request_requestID`),
  INDEX `fk_Hospital_has_Request_Request1_idx` (`Request_requestID` ASC) VISIBLE,
  INDEX `fk_Hospital_has_Request_Hospital1_idx` (`Hospital_hospital_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_has_Request_Hospital1`
    FOREIGN KEY (`Hospital_hospital_ID`)
    REFERENCES `mydb`.`Hospital` (`hospital_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Request_Request1`
    FOREIGN KEY (`Request_requestID`)
    REFERENCES `mydb`.`Request` (`requestID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET FOREIGN_KEY_CHECKS=0;

insert into mydb.blood_donors(name,surname,city,contactNo) values ("james","thompson","New York",90341257);
insert into mydb.blood_donors(name,surname,city,contactNo) values ("Johnny","bolt","Koln",902123201);
insert into mydb.blood_donors(name,surname,city,contactNo) values ("bekir","toprak","Berlin",9013205);

insert into mydb.recipients(bloodType,contactNO,quantityBlood,location) values ('brh-',453125,10,"sad");
insert into mydb.recipients(bloodType,contactNO,quantityBlood,location) values ('arh+',5058544,5,"sad");
insert into mydb.recipients(bloodType,contactNO,quantityBlood,location) values ('abrh-',9055351,2,"sad");

insert into mydb.hospital(name,address,location,city,phoneNo) values ("Tepecik Devlet Hastanesi","1800/1 street","Esbaş","Izmir",2321265);
insert into mydb.hospital(name,address,location,city,phoneNo) values ("Çiğli Devlet Hastanesi","965/2 sokak","Çiğli","Izmir",231353);
insert into mydb.hospital(name,address,location,city,phoneNo) values ("Medipol Hastanesi","574 sokak","Bahçelievler","Istanbul",1213442);

insert into mydb.blood(status,quantity,blood_group,blood_donors_DonorID,recipients_recipientsID) values ('Available',10,"arh-",452,512);
insert into mydb.blood(status,quantity,blood_group,blood_donors_DonorID,recipients_recipientsID) values ('Non-available',3,"brh-",2,3);
insert into mydb.blood(status,quantity,blood_group,blood_donors_DonorID,recipients_recipientsID) values ('Available',4,"0rh-",7,8);

insert into mydb.hospital_has_request(Hospital_hospital_ID,Request_requestID) values (301,124);
insert into mydb.hospital_has_request(Hospital_hospital_ID,Request_requestID) values (106,701);
insert into mydb.hospital_has_request(Hospital_hospital_ID,Request_requestID) values (158,381);

insert into mydb.request(name,requiredBlood,memberType,quantity,contactNO,location,seeker_seekerID) values ("Recep Toprak","yes","a",15,1212121,"Esbaş",124);
insert into mydb.request(name,requiredBlood,memberType,quantity,contactNO,location,seeker_seekerID) values ("Selahattin Yalınat","yes","a",15,1212121,"Çiğli",701);
insert into mydb.request(name,requiredBlood,memberType,quantity,contactNO,location,seeker_seekerID) values ("Murat Göğebakan","yes","a",15,1212121,"Bahçelievler",381);

insert into mydb.seeker(name,age,city,bloodgroup,gender,phoneNO) values ("Dogan",31,"Izmir","brh-","erkek",9053153);
insert into mydb.seeker(name,age,city,bloodgroup,gender,phoneNO) values ("batuhan",35,"Izmir","abrh+","erkek",9015321);
insert into mydb.seeker(name,age,city,bloodgroup,gender,phoneNO) values ("ibrahim",38,"Istanbul","0rh+","erkek",903653153);
SET FOREIGN_KEY_CHECKS=1;